[{"commit":{"message":"Replaced System.exit() with exception."},"files":[{"filename":"test\/jtreg_test_thread_factory\/src\/share\/classes\/Virtual.java"}],"sha":"b0878f35a77d2b72da1bc196b8a9ab9d42e9b2ad"},{"commit":{"message":"8318839: Update test thread factory to catch all exceptions"},"files":[{"filename":"test\/hotspot\/jtreg\/TEST.groups"},{"filename":"test\/jdk\/ProblemList-Virtual.txt"},{"filename":"test\/jdk\/java\/util\/concurrent\/tck\/ThreadTest.java"},{"filename":"test\/jtreg_test_thread_factory\/src\/share\/classes\/Virtual.java"}],"sha":"8fbb2798b0a66dc309587aa704772d8b38527ef5"}]