[{"commit":{"message":"add bug id 8334332 to jtreg tag @bug"},"files":[{"filename":"test\/langtools\/jdk\/javadoc\/doclet\/testIOException\/TestIOException.java"}],"sha":"92fc510ac1fc9d66914d2f38afe6f0440233db2d"},{"commit":{"message":"throw error()  ->  throw skip()"},"files":[{"filename":"test\/langtools\/jdk\/javadoc\/doclet\/testIOException\/TestIOException.java"}],"sha":"a9a770f2c3c1a7be06fb451c35bf6a0c0173d38d"},{"commit":{"message":"delete an extra whitespace"},"files":[{"filename":"test\/langtools\/jdk\/javadoc\/doclet\/testIOException\/TestIOException.java"}],"sha":"30916158e3ae227c9f5510770a0aefe0d3ec3c10"},{"commit":{"message":"8334332: TestIOException.java fails run with root user"},"files":[{"filename":"test\/langtools\/jdk\/javadoc\/doclet\/testIOException\/TestIOException.java"}],"sha":"24b4f6f95a0646d79a25165275b964faf8475575"}]