[{"commit":{"message":"fixed comment"},"files":[{"filename":"test\/hotspot\/jtreg\/runtime\/cds\/appcds\/aotCache\/VerifierFailOver_Helper.jcod"}],"sha":"674e130133382d1f4b85ce0de50d3af28071ac16"},{"commit":{"message":"8356318: Unexpected VerifyError in AOT training run"},"files":[{"filename":"src\/hotspot\/share\/classfile\/verifier.cpp"},{"filename":"test\/hotspot\/jtreg\/runtime\/cds\/appcds\/aotCache\/VerifierFailOver.java"},{"filename":"test\/hotspot\/jtreg\/runtime\/cds\/appcds\/aotCache\/VerifierFailOver_Helper.jcod"},{"filename":"test\/lib\/jdk\/test\/lib\/cds\/SimpleCDSAppTester.java"}],"sha":"c7bb36357bdb8be9f6b03d612405a7084f5dd167"}]